### ISSUE TITLE
Styling glitched on IE11

### ISSUE THREAD

**Issue by JordiVanOs** [ngx-toggle/ngx-toggle#1]
The buttons seems to have glitched styling on Internet Explorer 11, which is severe enough to make the labels unreadable or non-functional. Below I have included a screenshot of the demo page (https://ngx-toggle.github.io/#/components/toggle/examples) for ngx-toggle, taken on IE11.

The width of the labels seem to be too small, and the handle's width is also smaller than it's supposed to be.

![image](https://user-images.githubusercontent.com/18602016/39627911-a81cea06-4fa7-11e8-8bdd-8e2652f92fca.png)

**Comment by trickeyone** [comment]
Hrm... looks like IE11 isn't properly honoring CSS width of "auto" for the width calculations. I'll look into it. Thanks @Martionex!

**Comment by JordiVanOs** [comment]
Thank you @trickeyone ! Could you give me an update on your progress? It would be nice to get a fix for this problem, as the platform I am developing for has to use IE11, and I really like the looks of ngx-toggle compared to alternative switch components.

**Comment by trickeyone** [comment]
I've been trying to track the issue down. I work on a Mac and, so I've been having issues trying to test and find the problem. I have to rely on running tests through Saucelabs. I can boot a VM up through it, but for a limited amount of time. So testing is taking a while. Along with my regular job and life, I'm trying to find more time to track this down. I'll try to do some more testing on it tonight or over the weekend.
Bootstrap v4 uses flexbox, which it appears IE only partially supports, so this might part of the issue.
I'll try to keep you updated on what I find out.

**Comment by trickeyone** [comment]
This issue should be resolved. Took me a little while to get a testing environment for IE11.

Released a new version (v1.0.2) and published to npm.

**Comment by JordiVanOs** [comment]
@trickeyone Thank you very much for the fix!
