### ISSUE TITLE
[Feature] Support custom classes

### ISSUE THREAD

**Issue by theCrius** [ngx-toggle/ngx-toggle#10]
### Feature description:
As far as I've seen the styling for width is applied in a "style" tag applied to the "toggle-on", "handle" and 'toggle-off' and the rest relies on bootstrap classes.

Would it will be possible to expose an `onClass`, `offClass` and `handleClass` that should be injected after the regular classes set by default?

Those three attributes would apply to the three root elements of the toggle, `ng-toggle-on`, `ng-toggle-handle`, `ng-toggle-off`:
```
<span class="ng-toggle-container" style="margin-left: 0px; width: 112px;">
    <span class="ng-toggle-on btn btn-success" style="width: 48px;">On</span>
    <span class="ng-toggle-handle btn btn-light">&nbsp;</span>
    <span class="ng-toggle-off btn btn-danger" style="width: 48px;">Off</span>
</span>
```
So for example something like this:
```
<ng-toggle
            [(ngModel)]="toggleModel"
            handleClass="custom-handle-class"
            onColor="success"
            onClass="custom-on-class"
            offColor="danger"
            offClass="custom-off-class"
          >
```

would render to something like:
```
<span class="ng-toggle-container" style="margin-left: 0px; width: 112px;">
    <span class="ng-toggle-on btn btn-success custom-on-class" style="width: 48px;">On</span>
    <span class="ng-toggle-handle btn btn-light custom-handle-class">&nbsp;</span>
    <span class="ng-toggle-off btn btn-danger custom-off-class" style="width: 48px;">Off</span>
</span>
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.7

ng-bootstrap: 4.0.4

Bootstrap: 4.3.1

**Comment by trickeyone** [comment]
@theCrius Have you tried using the Custom Label option? https://nth-cloud.github.io/ng-toggle/#/docs/examples#custom-label

It allows you to supply your own On/Off labels, including styling.

Or you could try using control styling. In your calling component you could have something similar to:

```typescript
@Component({
    selector: 'my-component',
    templateUrl: ...
})
export class MyComponent {
  model: any = {
    onText: 'On',
    offText: 'Off',
    disabled: false,
    value: null
  };
}
```

```html
<ng-toggle [(ngModel)]="toggleModel">
    <ng-template ngToggleLabel forLabel="on"><div [style.width.px]="64">{{model.onText}}</div></ng-template>
    <ng-template ngToggleLabel forLabel="off"><div [style.width.px]="64">{{model.offText}}</div></ng-template>
</ng-toggle>
```

**Comment by theCrius** [comment]
Ah I see! That definitely is a much powerful customization option!

My whole suggestion however started because I wanted to style the handle and I thought "well, the same principle could be applied to the on/off as well".

I had a request to thin the handle a little but seeing that the width is calculated and applied I figured I could have played with other css attributes but couldn't find any way of styling it using any API.

I suppose I'll have to inject some css in the class for that, then.

Thanks anyway and big props for this very good component 👍
