### ISSUE TITLE
Angular 9 console errores

### ISSUE THREAD

**Issue by integraitco** [ngx-toggle/ngx-toggle#23]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/nth-cloud/ng-toggle/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
After updating my projecto to Angular 9 Im getting this error in console.

index-add-edit.component.html:165 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at NgToggle.get container$ [as container$] (ng-toggle.js:456)
    at NgToggle.calculateWidth (ng-toggle.js:390)
    at NgToggle.ngOnChanges (ng-toggle.js:167)
    at checkAndUpdateDirectiveInline (core.js:32900)
    at checkAndUpdateNodeInline (core.js:45701)
    at checkAndUpdateNode (core.js:45640)
    at debugCheckAndUpdateNode (core.js:46663)
    at debugCheckDirectivesFn (core.js:46606)
    at Object.updateDirectives (index-add-edit.component.html:172)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:46594)

### Link to minimally-working StackBlitz that reproduces the issue:

https://angular-prr5xh.stackblitz.io
https://stackblitz.com/edit/angular-prr5xh

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 
9.0.2
ng-bootstrap:

Bootstrap:

**Comment by markosankovic** [comment]
This is related to https://angular.io/guide/static-query-migration. Starting with version 9, the static flag will default to `false`. That means the `containerElement` will be undefined in the first call to `ngOnChanges`.

**Comment by trickeyone** [comment]
I haven't had time to look at supporting Angular 9 yet. I'll try to get to it as soon as I can.

**Comment by andlewis** [comment]
Any update on this one?

**Comment by trickeyone** [comment]
Nothing yet. My main job has been keeping me busy. I'll try to add Angular 8 & 9 support as soon as I can.

**Comment by philjones88** [comment]
@trickeyone I've had a go at upgrading to Angular 8 that should fix most of the issues with angular 9? See https://github.com/nth-cloud/ng-toggle/pull/24

Welcome to your feedback, I just made the best decisions I could to get it migrated.

**Comment by trickeyone** [comment]
Thanks for doing that, @philjones88 ! It looks really good, I just had one comment on it. Please look at the PR. Once the changes are done, I'll get it merged and deploy a new build.

Edit:
Nvm, don't know what I was thinking. I'll just merge and update. Thanks for the work again, @philjones88 !
