### ISSUE TITLE
Is it possible to refuse to switch the state?

### ISSUE THREAD

**Issue by vslugin** [ngx-toggle/ngx-toggle#27]
I apologize for asking instead of a problem, but couldn't find another way to ask it.

How to add functionality to prevent the toggler from switching inside the callback to a nickname or change?

For example, throw confirm when trying to switch the toggler, and if the user refused, then do not switch the toggler

**Comment by trickeyone** [comment]
I'm not sure I understand what you're asking. Are you asking if there's a way to disable the toggle? Can you provide a stackblitz or some example of what you're looking to accomplish?
