### ISSUE TITLE
Allow users to customize handle

### ISSUE THREAD

**Issue by topalavlad** [ngx-toggle/ngx-toggle#28]
### Feature description:

Sometimes the `ng-toggle` handle color is much too similar to the background so it becomes confusing for users.
Could the handle colors (hover and non-hover) be customisable as the other colors are?

**Comment by trickeyone** [comment]
I can look into this. It'd be a little more difficult maybe, just due to how Angular bindings work.

**Comment by topalavlad** [comment]
I kind of hacked my way into a fix by overwriting the `background-color` of `ng-toggle-handle` in `global.scss` but customising would be useful.

**Comment by trickeyone** [comment]
@topalavlad Just wanted to let you know I haven't forgotten about this. As I suspected, it's proving harder to accomplish than it appears. Doing binding on a dynamic value is more difficult than anticipated. I'm working on it and hope to have something available soon.
