### ISSUE TITLE
Make toggle work in 3 steps instead of 2

### ISSUE THREAD

**Issue by cascesme** [ngx-toggle/ngx-toggle#29]
Is there a way of adding a configuration to make toggle work with 3 steps. Instead of passing from true to false back and forth. Can we pass from true to false / from false to null / null to true. I tried using` (valueChanged)` and manually setting the model to null but it didn't work. Thank you for your time.

**Comment by trickeyone** [comment]
@CesarUCIGIT It does work with 3-stages. If you look at the docs, you'll see how to accomplish this: https://nth-cloud.github.io/ng-toggle/#/docs/examples#kitchen-sink

Setting the modal value to `null` puts the toggle into the indeterminate state.

**Comment by cascesme** [comment]
Yes but once you pass from null to true and false it never comes back to indeterminate. I tried using (value changed) and then forcing it to be null when it comes from false state but it didn't work as I expected. Is it possible to add flag to say that we want 3 steps in stages?

**Comment by trickeyone** [comment]
@CesarUCIGIT Can you provide an expected test case? I'm not following what you're wanting to accomplish. The component is a toggle, which indicates 2 states. You can set the model to equal `null` which will put the component into the aforementioned indeterminate state. Other than that, I'm not following what you're wishing to accomplish.
