### ISSUE TITLE
Visual glitch when generating multiple toggle elements

### ISSUE THREAD

**Issue by jmsalajka** [ngx-toggle/ngx-toggle#3]
When I use ngFor to generate multiple ngx-toggle elements, I can see the toggle elements shrinking from the width of the whole row. It's not breaking anything, but it's a pretty noticeable change, and when I want the toggles to be in the same row as another form element, the page elements shift while the toggles resize.

**Comment by trickeyone** [comment]
Hi @jmsalajka . Have you tried using ng-container or wrapping the toggle inside another element (i.e. a div or inline-block element)? I've seen this issue with other Angular components when using ngFor on the component itself.

**Comment by jmsalajka** [comment]
That limits the magnitude of the issue. It's not taking up the whole row anymore, but it still loads in about twice as large as it would be - the toggles appear to load in with the On and Off sides both at their maximum width. The issue only occurs when the toggles initially load; other than this, they work perfectly.

**Comment by trickeyone** [comment]
Can you provide an example that outlines the issue? i.e. a plunkr example, etc.

**Comment by jmsalajka** [comment]
Here's a plunker demo - https://plnkr.co/FRMvhHp23XAyExoAkLh6.

We have the toggles wrapped in a div with class="d-inline-flex", which reduces the impact of the issue, but you can still see the switch shrink upon loading.

**Comment by jmsalajka** [comment]
I should probably note that the issue has been observed on both Chrome and Firefox, as well as Internet Explorer. I haven't tested on Edge or Safari, unfortunately.

**Comment by trickeyone** [comment]
@jmsalajka I checked out your plunkr in Chrome (67.0.3396.99) and Firefox (60.0.2). I'm not sure I understand what you're saying is the issue. They all look to be the correct width.

I use this component, myself, in an inline context. Of course, we're using it inside a Bootstrap "col" div, so the element itself isn't inline. But I haven't seen any weird shrinking issues.

If you can give me more information on what you're seeing, it would be very helpful.

**Comment by jmsalajka** [comment]
When I load the plunkr, the toggle element very briefly fills the entire row it inhabits. It's very quick. For switches with a default state "off", this is seen as a long grey bar on the screen extending outward from the right of a toggle component.

I'm using this component as a toggle on a settings page - usually it is the only item on its line (besides a line header) and there are usually several on the page. When it's just one or two, the effect isn't particularly noticeable (and we've managed to reduce the effect by using the d-inline-flex class in the container div), but we frequently have upwards of five of these components loaded onto a page at once. Those lower on the page very visibly look like this:

![image](https://user-images.githubusercontent.com/39921042/42662062-c8ad3c24-85f5-11e8-82de-5a4d6fe55652.png)

Hope this helps.

**Comment by trickeyone** [comment]
It looks like the plunkr is no longer available. If you can recreate it or provide a newer example I'll continue to look into this issue.
