### ISSUE TITLE
Angular 15 compatibility

### ISSUE THREAD

**Issue by fatcatt013** [ngx-toggle/ngx-toggle#49]
Is this a plan anytime soon? I am upgrading from Angular 13 to 15 and I use this library in my project.

**Comment by WojciechNagorski** [comment]
+1

**Comment by trickeyone** [comment]
@fatcatt013 & @WojciechNagorski ignore stalebot. This did slip off my radar, but stalebot reminded me. I'm having to upgrade from v13 -> v14 -> v15 one at a time. v14 is done and a new version is up. I'll try to get v15 done this weekend. Sorry for the severe delay.

**Comment by trickeyone** [comment]
@fatcatt013 @WojciechNagorski Angular 15 is now supported by ng-toggle 11.0.0

Sorry again it took so long. Work and personal life got in the way.
