### ISSUE TITLE
Upgrade to Angular 6

### ISSUE THREAD

**Issue by bostondevin** [ngx-toggle/ngx-toggle#5]
It works with Angular 6, but I get these warnings:

npm WARN ngx-toggle@1.0.2 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toggle@1.0.2 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toggle@1.0.2 requires a peer of @angular/forms@^5.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by trickeyone** [comment]
Thanks for the report. I hadn't looked at Angular v6 yet. I will try to get to running tests with v6 and get a new release out soon
