### ISSUE TITLE
Need instructions on how to handle the event 

### ISSUE THREAD

**Issue by gopal-g** [ngx-toggle/ngx-toggle#7]
The documentation suggests that `valueChange` will be fired when the user toggles the button , Can you share an example with usage of the callback.

I tried using valueChange just like other options of the plugin and catch the event, But nothing happens.

Angular version : 6.0
ngx-toggle version: 2.0.1

**Comment by trickeyone** [comment]
@gopal-g Can you provide an example of what you're referring to? You can use the output `(valueChange)` or use the `ngModel` method.

**Comment by gopal-g** [comment]
I want to be able to trigger a method/function in the component when user toggles the button. 

suppose this is my component HTML 
```
<ngx-toggle name="verifiedToggle" onColor="{{verifiedToggle.onColor}}" onText="{{verifiedToggle.onText}}"
                    offColor="{{verifiedToggle.offColor}}" offText="{{verifiedToggle.offText}}" [disabled]="verifiedToggle.disabled"
                    [size]="verifiedToggle.size" [(ngModel)]="verifiedToggle.value">
                  </ngx-toggle>
```
this is my component 

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})

export class AppComponent  {

  name = 'Angular';
  
  actualToggleValue = "NO";

  public verifiedToggle = {
        'onColor': 'success',
        'offColor': 'secondary',
        'onText': 'Yes',
        'offText': 'No',
        'disabled': false,
        'size': 'sm',
        'value': false
    };

  onToggle(state){
     console.log("current toggle state is ", state);
     this.actualToggleValue = state ? "YES" : "NO";
  }

}


```

How do i trigger the onToggle function in order to track the toggle status ? Cause i want to set the value of the actualToggleValue variable instead of true or false.

**Comment by trickeyone** [comment]
Hi @gopal-g .
Do you understand Angular output events and how to use them?
If not, I'd suggest looking at https://angular.io/guide/component-interaction#parent-listens-for-child-event It explains how to hook into the `(valueChange)` Output Event

If you're simply wanting to display a value based on the boolen result, I suggest checking out this Angular guide fir various methods: https://angular.io/guide/component-interaction

**Comment by gopal-g** [comment]
Thank you for this I had no idea, Will have a look and try it out.
