### ISSUE TITLE
Incorrect width

### ISSUE THREAD

**Issue by originals** [ngx-toggle/ngx-toggle#8]
When adding the toggle button it has a width of 0
![Image](https://i.imgur.com/K76Bbef.png)

it has something to do with updating the with icw initialize state because removing the following if statement around:
            // if (!initialized) {
                _this.container$.style.width = ((_this.width * 2) + _this.handleWidth) + 'px';
                _this.wrapper$.style.width = (_this.width + _this.handleWidth) + 'px';
            // }

gives me a proper button
![Image](https://i.imgur.com/nCl78dm.png)

**Comment by trickeyone** [comment]
That appears to be because you're attempting to forcibly change the element's dimensions before the component is initialized. This does not appear to be an issue with the component, but with your implementation.

**Comment by trickeyone** [comment]
Can you give some more information on this? The tests and demos all work. If you can provide more information on how your implementing it, I might be able to assist.

**Comment by originals** [comment]
Ur right, it has something to do with my module structure and how im importing it i think, in the login component it works ok:

login.module.ts:
```typescript
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {RouterModule} from '@angular/router';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {LoginComponent} from './login.component';
import {SharedModule} from '../../shared.module';
import {NgxToggleModule} from 'ngx-toggle';


export const routes = [
    {path: '', component: LoginComponent, pathMatch: 'full'}
];

@NgModule({
    imports: [
        CommonModule,
        SharedModule,
        NgxToggleModule,
        FormsModule,
        ReactiveFormsModule,
        RouterModule.forChild(routes)
    ],
    declarations: [
        LoginComponent
    ]
})

export class LoginModule {
}

```

shared.module.ts:
```typescript
import {NgModule} from '@angular/core';
import {FlagsMenuComponent} from './framework/components/login-settings/flags-menu/flags-menu.component';
import {FullScreenComponent} from './framework/components/fullscreen/fullscreen.component';
import {ThemeSelectComponent} from './framework/components/login-settings/theme-select/theme-select.component';
import {PasswordInputComponent} from './framework/components/input-fields/password/password.component';
import {CommonModule} from '@angular/common';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {ConnectionStatusComponent} from './framework/components/connection-status/connection-status.component';
import {LoginSettingsComponent} from './framework/components/login-settings/login-settings.component';
import {KeyboardToggleComponent} from './framework/components/login-settings/keyboard-toggle/keyboard-toggle.component';
import {NgxToggleModule} from 'ngx-toggle';

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        NgxToggleModule,
    ],
    declarations: [
        FlagsMenuComponent,
        FullScreenComponent,
        ThemeSelectComponent,
        PasswordInputComponent,
        ConnectionStatusComponent,
        LoginSettingsComponent,
        KeyboardToggleComponent],
    exports: [
        FlagsMenuComponent,
        FullScreenComponent,
        ThemeSelectComponent,
        PasswordInputComponent,
        ConnectionStatusComponent,
        LoginSettingsComponent,
        KeyboardToggleComponent]
})
export class SharedModule {
}
```

in the KeyboardToggleComponent its not working correctly, which is used by the login component

**Comment by trickeyone** [comment]
I think it might be your import order. I've run into that before on other projects. Try to order your imports by dependency. i.e. Don't import a component/module that requires another dependency before you import that dependency.

**Comment by originals** [comment]
whatever order i choose for the nested component, i cant get it to work for the exported components.

**Comment by originals** [comment]
When i add the component which has the toggle button out of the tab-pane of bootstrap it works, somehow its related to nav-tabs, which are not initially loaded
then the width will be 0 when ngAfterViewInit etc occurs

ive made myself a workaround where i just set the container/wrapper width myself as input
