### ISSUE TITLE
Angular 7.0+ Compatibility

### ISSUE THREAD

**Issue by andlewis** [ngx-toggle/ngx-toggle#9]
Installing in an Angular 7.0 project gives the following warnings:

npm WARN ngx-toggle@2.0.1 requires a peer of @angular/common@^6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toggle@2.0.1 requires a peer of @angular/core@^6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-toggle@2.0.1 requires a peer of @angular/forms@^6.1.10 but none is installed. You must install peer dependencies yourself.

**Comment by trickeyone** [comment]
Hi @andlewis . As indicated on the README, it's only been tested with up to Angular v6.1.10. Angular v7 was just released. I'll look at upgrading to v7.

**Comment by trickeyone** [comment]
An upgraded version is now available for Angular v7+. Please use `@nth-cloud/ng-toggle` from now on.
